### ISSUE TITLE
removing alarm control panel constants breaks my alarm control pannels, They now show up as "Unknown"

### ISSUE THREAD

**Issue by yougotborked** [jason0x43/hacs-hubitat#296] opened 2024-11-16 05:25 UTC
**Describe the bug**
I upgraded to 9.37 and all my synced alarm control panels are not able to be controlled anymore in HA. And their status shows up as unknown and an error appears when I try to change their alarm state. I rolled back to 9.34 as a test and it started working again.

I think its because of this change
https://github.com/jason0x43/hacs-hubitat/commit/0d50ea0bfc3d77e83147613dc262b1f56f7402be

**To Reproduce**

Happens immediately on upgrade.

**Screenshots**

**Environment**

 - Home Assistant version: 2024.11.2
 - Integration version: 9.37

**Comment by jason0x43** [comment] 2024-11-16 06:27
Yikes! If possible, could you update again and post any errors that show up in the logs?

**Comment by yougotborked** [comment] 2024-11-16 19:33
Yes it looks like this might be the error
Logger: homeassistant.components.alarm_control_panel
Source: components/alarm_control_panel/__init__.py:210
integration: Alarm control panel (documentation, issues)
First occurred: 1:32:47 PM (6 occurrences)
Last logged: 1:32:49 PM

Entity alarm_control_panel.home_alarm (<class 'custom_components.alarmo.alarm_control_panel.AlarmoAreaEntity'>) is setting state directly which will stop working in HA Core 2025.11. Entities should implement the 'alarm_state' property and return its state using the AlarmControlPanelState enum, please report it to the custom integration author.
Entity alarm_control_panel.smoke_alarm (<class 'custom_components.alarmo.alarm_control_panel.AlarmoAreaEntity'>) is setting state directly which will stop working in HA Core 2025.11. Entities should implement the 'alarm_state' property and return its state using the AlarmControlPanelState enum, please report it to the custom integration author.
Entity alarm_control_panel.water_alarm (<class 'custom_components.alarmo.alarm_control_panel.AlarmoAreaEntity'>) is setting state directly which will stop working in HA Core 2025.11. Entities should implement the 'alarm_state' property and return its state using the AlarmControlPanelState enum, please report it to the custom integration author.
Entity None (<class 'custom_components.hubitat.alarm_control_panel.HubitatSecurityKeypad'>) is setting state directly which will stop working in HA Core 2025.11. Entities should implement the 'alarm_state' property and return its state using the AlarmControlPanelState enum, please report it to the custom integration author.

**Comment by yougotborked** [comment] 2024-11-16 19:39
[33m2024-11-16 13:32:49.649 WARNING (MainThread) [homeassistant.components.alarm_control_panel] Entity None (<class 'custom_components.hubitat.alarm_control_panel.HubitatSecurityKeypad'>) is setting state directly which will stop working in HA Core 2025.11. Entities should implement the 'alarm_state' property and return its state using the AlarmControlPanelState enum, please report it to the custom integration author.[0m

**Comment by jason0x43** [comment] 2024-11-27 04:53
I believe you're right. It looks like AlarmControlPanel is switching to a new enum-based state value, and it temporarily ignored the existing `_attr_state` value, which is what this integration was using.

If you get a chance, could you try out [v0.9.38-pre0](https://github.com/jason0x43/hacs-hubitat/releases/tag/v0.9.38-pre0) and see if that behaves a bit better? It should support both the existing state attr as well as the new one.

**Comment by jason0x43** [comment] 2024-12-21 21:38
Closing this since the issue is resolved

**Closed by jason0x43** 2024-12-21 21:38 UTC
