### ISSUE TITLE
Z - wave Ring Range Extender missing entities after update

### ISSUE THREAD

**Issue by DeekB1983** [jason0x43/hacs-hubitat#239] opened 2024-01-02 20:17 UTC
I have Z wave ring range extender on my hubitat hub, it is being passed through to Home assistant via the integration.

It looks like it stopped reporting the powerSource entity when it was updated, this should state ether mains or battery.
![image](https://github.com/jason0x43/hacs-hubitat/assets/64811870/32d631c6-8e7e-4a15-8fad-8f25eccecc42)

![image](https://github.com/jason0x43/hacs-hubitat/assets/64811870/70d798a1-8545-4c40-a9e9-9080e9a3982f)

I am running the latest version that seems to have been released today but lookslike the problem started on the 1st of Jan after an update then.

I was wondering if there was a reason why its missing and if this entity can be restored please?

**Comment by jason0x43** [comment] 2024-01-02 23:16
The logic that names entities was updated in the integration more closely align with how Home Assistant works, and there have been a few issues. The entity wasn't removed intentionally, and it will definitely be restored. 🙂 

If you click the `+1 entity not shown` link in the Sensors block, what do you get? If it's another power entity, what is the name of the entity (e.g., `sensor.range_extender_power`)? Also, what is the name of the entity that is no longer available?

**Comment by DeekB1983** [comment] 2024-01-02 23:36
thats great to know, thanks.

The entity under not shown seems to be last updated.
![image](https://github.com/jason0x43/hacs-hubitat/assets/64811870/1bdf9960-5afa-4447-ade8-b57f9eb52568)


The entity names are as follows:
sensor.ring_range_extender_powersource
sensor.ring_range_extender_last_update_time

Both of above seem to be unavailable.

**Comment by jason0x43** [comment] 2024-01-03 01:40
Possibly the issue was related to some issues around entity unique IDs. See if things are working again with v0.9.17.

**Comment by DeekB1983** [comment] 2024-01-03 09:44
> Possibly the issue was related to some issues around entity unique IDs. See if things are working again with v0.9.17.

Hi Jason,

I installed V0.9.17 this morning and restarted home assistant but stll the same issue.
![image](https://github.com/jason0x43/hacs-hubitat/assets/64811870/61e56d34-2ffb-4f26-b72a-d78ec7f684e2)

**Comment by jason0x43** [comment] 2024-01-03 14:41
Hmmm… Could you try gathering a couple pieces of information?

1. Get the [device capabilities](https://github.com/jason0x43/hacs-hubitat#checking-device-capabilities)
2. Enable [debug logging](https://github.com/jason0x43/hacs-hubitat#logging), interact with the device a bit, and see what update events are received in the log.

This information will help diagnose exactly what has changed related to your device.

**Comment by jason0x43** [comment] 2024-01-05 02:49
Based on the errors in #246 and the fact that your problematic entity is a power source, I'm pretty sure I know what the issue is, and a fix will be out soon.

**Comment by jason0x43** [comment] 2024-01-05 03:42
The power level issue should be fixed in v0.9.19. Let me know if you're still seeing issues with the Last Update Time (that should be working).

**Comment by DeekB1983** [comment] 2024-01-05 11:01
> The power level issue should be fixed in v0.9.19. Let me know if you're still seeing issues with the Last Update Time (that should be working).

Hey Jason,

thanks for this, the entity is now working as it was before but the last updated time is still unavailable.
![image](https://github.com/jason0x43/hacs-hubitat/assets/64811870/d400febd-fc84-4059-b5a7-1b2aae5cefee)
![image](https://github.com/jason0x43/hacs-hubitat/assets/64811870/b0279847-4abc-4207-a7ee-070334dd7b5f)

I wasnt using the last updated time and its not and issue for me so I would be happy to close the issue down but you may want to understand\fix the issue so I havent closed it yet!

**Comment by jason0x43** [comment] 2024-01-05 15:24
I’m glad to hear the power source sensor is working, but I’m curious about the update sensor. Do you see any errors in your Home Assistant log related to that sensor? Maybe an error related to converting a sensor value or something?

**Comment by jason0x43** [comment] 2024-03-31 02:17
I'm closing this since there haven't been any updates in a while.

**Closed by jason0x43** 2024-03-31 02:17 UTC
