### ISSUE TITLE
Z-wave thermostat setpoint

### ISSUE THREAD

**Issue by kerrylarson** [jason0x43/hacs-hubitat#299] opened 2024-11-27 20:43 UTC
I am trying to set a Z-wave thermostat to a low heat setpoint (i.e. 40F to prevent a room from freezing).  HASS, apparently from the Hubitat integration, prevents setting a value below 45.  I have to go back to Hubitat set set a target temperature below 45.  This is not a limitation in the thermostat itself (Radio Thermostat CT101).  Is there a simple way to resolve this?

I tried to customize an Actions YAML, but since I don't know what I'm doing, I got a syntax error:
action:
  - service: sensor.shop_thermostat_thermostat_setpoint
    target:
      entity_id: climate.shop_thermostat
    data:
      target_temp_high: 75
      target_temp_low: 35
      hvac_mode: heat_cool

**To Reproduce**

Go to thermostat device.  Set a heat setpoint above 45F.  Try to set a new heat setpoint of 40F - no go.

**Environment**
Core 2024.11.3
Supervisor 2024.11.4
Operating System 13.2
Frontend 20241106.2

**Comment by jason0x43** [comment] 2024-11-27 21:29
Currently the integration is using HA's default min and max temperatures, but it looks like we could provide different ones. I should be able to just lower the min temperature for the integration down to 40°F.

**Comment by kerrylarson** [comment] 2024-11-27 22:06
"Currently the integration is using HA's default min and max temperatures"  Oh, I read an old thread on the topic that pointed to a Z-wave device issue, so I mistakenly assumed that was it.  I just tried with a WIFI thermostat and see that you're completely right, it's also limited to 45F, so coming from HA.  Can that be adjusted in the configuration.yaml?

**Comment by jason0x43** [comment] 2024-11-27 22:36
I just tried customizing an entity through configuration.yaml, and while it changes the range for the UI control, HA won't accept numbers outside the 7/35°C range. Updating the min temperature in the integration's climate entity works, though. I'll try to post an update with that later today.

**Comment by jason0x43** [comment] 2024-11-28 04:32
v0.9.38 has been updated to support a minimum thermostat temperature of 40°F. Give that a try.

**Comment by kerrylarson** [comment] 2024-11-28 04:56
It works!  Thanks so much Jason for helping me out.  At least for this thermostat, it appears that the lower limit is 35°F.

**Comment by jason0x43** [comment] 2024-11-28 05:02
If you have a chance, could you post the [capabilites](https://github.com/jason0x43/hacs-hubitat/tree/v0.9.38-pre0?tab=readme-ov-file#checking-device-capabilities) for your thermostat device? I'm wondering if the device indicates its min and max temperatures.

**Comment by kerrylarson** [comment] 2024-11-28 05:29
`
[
    {
        "capabilities": [
            "RelativeHumidityMeasurement",
            {
                "attributes": [
                    {
                        "name": "humidity",
                        "currentValue": "41",
                        "dataType": "NUMBER",
                        "values": null
                    }
                ]
            },
            "ThermostatFanMode",
            {
                "attributes": [
                    {
                        "name": "thermostatFanMode",
                        "currentValue": "fanAuto",
                        "dataType": "ENUM",
                        "values": [
                            "on",
                            "circulate",
                            "auto"
                        ]
                    }
                ]
            },
            "PowerSource",
            {
                "attributes": [
                    {
                        "name": "powerSource",
                        "currentValue": "mains",
                        "dataType": "ENUM",
                        "values": [
                            "battery",
                            "dc",
                            "mains",
                            "unknown"
                        ]
                    }
                ]
            },
            "Refresh",
            "Battery",
            {
                "attributes": [
                    {
                        "name": "battery",
                        "currentValue": "100",
                        "dataType": "NUMBER",
                        "values": null
                    }
                ]
            },
            "ThermostatHeatingSetpoint",
            {
                "attributes": [
                    {
                        "name": "heatingSetpoint",
                        "currentValue": "40",
                        "dataType": "NUMBER",
                        "values": null
                    }
                ]
            },
            "ThermostatCoolingSetpoint",
            {
                "attributes": [
                    {
                        "name": "coolingSetpoint",
                        "currentValue": "78",
                        "dataType": "NUMBER",
                        "values": null
                    }
                ]
            },
            "ThermostatSetpoint",
            {
                "attributes": [
                    {
                        "name": "thermostatSetpoint",
                        "currentValue": "40",
                        "dataType": "NUMBER",
                        "values": null
                    }
                ]
            },
            "ThermostatOperatingState",
            {
                "attributes": [
                    {
                        "name": "thermostatOperatingState",
                        "currentValue": "idle",
                        "dataType": "ENUM",
                        "values": [
                            "heating",
                            "pending cool",
                            "pending heat",
                            "vent economizer",
                            "idle",
                            "cooling",
                            "fan only"
                        ]
                    }
                ]
            },
            "HealthCheck",
            {
                "attributes": [
                    {
                        "name": "checkInterval",
                        "currentValue": null,
                        "dataType": "NUMBER",
                        "values": null
                    }
                ]
            },
            "Configuration",
            "Actuator",
            "Polling",
            "ThermostatMode",
            {
                "attributes": [
                    {
                        "name": "thermostatMode",
                        "currentValue": "heat",
                        "dataType": "ENUM",
                        "values": [
                            "auto",
                            "off",
                            "heat",
                            "emergency heat",
                            "cool"
                        ]
                    }
                ]
            },
            "TemperatureMeasurement",
            {
                "attributes": [
                    {
                        "name": "temperature",
                        "currentValue": "44.5",
                        "dataType": "NUMBER",
                        "values": null
                    }
                ]
            },
            "Thermostat",
            {
                "attributes": [
                    {
                        "name": "temperature",
                        "currentValue": "44.5",
                        "dataType": "NUMBER",
                        "values": null
                    },
                    {
                        "name": "heatingSetpoint",
                        "currentValue": "40",
                        "dataType": "NUMBER",
                        "values": null
                    },
                    {
                        "name": "coolingSetpoint",
                        "currentValue": "78",
                        "dataType": "NUMBER",
                        "values": null
                    },
                    {
                        "name": "thermostatSetpoint",
                        "currentValue": "40",
                        "dataType": "NUMBER",
                        "values": null
                    },
                    {
                        "name": "thermostatMode",
                        "currentValue": "heat",
                        "dataType": "ENUM",
                        "values": [
                            "auto",
                            "off",
                            "heat",
                            "emergency heat",
                            "cool"
                        ]
                    },
                    {
                        "name": "thermostatFanMode",
                        "currentValue": "fanAuto",
                        "dataType": "ENUM",
                        "values": [
                            "on",
                            "circulate",
                            "auto"
                        ]
                    },
                    {
                        "name": "thermostatOperatingState",
                        "currentValue": "idle",
                        "dataType": "ENUM",
                        "values": [
                            "heating",
                            "pending cool",
                            "pending heat",
                            "vent economizer",
                            "idle",
                            "cooling",
                            "fan only"
                        ]
                    },
                    {
                        "name": "supportedThermostatModes",
                        "currentValue": "[\"heat\",\"cool\",\"off\",\"auto\"]",
                        "dataType": "JSON_OBJECT",
                        "values": null
                    },
                    {
                        "name": "supportedThermostatFanModes",
                        "currentValue": "[\"auto\",\"on\"]",
                        "dataType": "JSON_OBJECT",
                        "values": null
                    }
                ]
            },
            "Sensor"
        ]
    }
]
`

**Comment by kerrylarson** [comment] 2024-11-28 05:30
Sorry, I didn't get it formatted correctly.

**Comment by jason0x43** [comment] 2024-11-28 05:52
No problem, it just needed more back ticks 🙂

**Comment by jason0x43** [comment] 2024-12-21 21:37
Closing this since the issue is resolved

**Closed by jason0x43** 2024-12-21 21:37 UTC
