### ISSUE TITLE
hubitat no longer loads past home assistant version core-2021.5.5

### ISSUE THREAD

**Issue by jatgm1** [jason0x43/hacs-hubitat#126] opened 2021-06-28 20:46 UTC
hubitat doesnt load after core-2021.5.5. if i update it refuses to load. idk whats wrong but i need it to work for my whole smarthome lol.

**Comment by jason0x43** [comment] 2021-07-24 13:29
Is this still an issue? I haven't run into an issues using the integration with HA 2021.6 and 2021.7.

**Comment by jason0x43** [comment] 2021-08-11 15:44
Closing this since I've never been able to reproduce.

**Closed by jason0x43** 2021-08-11 15:44 UTC
