### ISSUE TITLE
Hub HSM Status and Hub Mode displaying as unknown in Dashboard

### ISSUE THREAD

**Issue by ryanquan** [jason0x43/hacs-hubitat#282] opened 2024-08-21 19:27 UTC
Hub HSM Status and Hub Mode displaying as unknown in Dashboard.  Not sure what's wrong, but Maker API is properly configured and Allow control of Modes and HSM are enabled.  When entering direct link of status in browser, it displays status values: http://***.****.****.****/apps/api/***/hsm?access_token=
{"hsm":"disarmed"}

![Screenshot 2024-08-21 122140](https://github.com/user-attachments/assets/5dad1af6-4490-4e07-bcf0-c4c751987143)

 - Home Assistant version: 2024.8.2
 - Integration version: 0.9.31

**Comment by PlinyElderATX** [comment] 2024-08-22 15:03
Try changing mode to something it's not then back through HA and see if that fixes it.

I noticed that you lose mode sometimes when restarting HA or Hubitat but it gets it back on the next change. I threw a discussion topic in on this as well as I wasn't sure it wasn't expected behavior: https://github.com/jason0x43/hacs-hubitat/discussions/281

**Comment by ryanquan** [comment] 2024-08-22 15:18
Cycling the Mode and HSM states in Hubitat doesn't change the status in HA.

**Comment by PlinyElderATX** [comment] 2024-08-22 21:03
Maybe try toggling these on then off and rebooting hubitat and then re-starting the integration in home assistant (after Hubitat is fully rebooted).

![image](https://github.com/user-attachments/assets/fc794da6-6ff1-4919-88b3-16939e8ebc15)

**Comment by sacua** [comment] 2024-08-27 22:32
I confirm this issue as well. On my side, the hubitat integration simply needs to be reloaded and the hsm status becomes unknown. It is still possible to send hsm command as previously said.

**Comment by sacua** [comment] 2024-08-27 22:51
The day I will spend more time to understand how integration are implemented I could make a pull request, but for the moment, I know that the status can be get at the followiong end point:
http://YOUR_HUBITAT_IP_ADDRESS/apps/api/YOUR_API_ID/hsm?access_token=YOUR_ACCESS_TOKEN

**Comment by PlinyElderATX** [comment] 2024-08-28 12:03
Seems like perhaps a load time change is needed to add a mode refresh. Also could add a periodic check to see if mode is null and refresh if so

**Comment by jason0x43** [comment] 2024-08-31 02:20
This should be resolved in v0.9.32. The problem was that the status and mode weren't being set when the integration was initially loaded. They were only set when the values were changed in Hubitat, causing an update event in Home Assistant.

**Closed by jason0x43** 2024-08-31 02:20 UTC

**Comment by ryanquan** [comment] 2024-08-31 02:32
Issue resolved.  Thanks for fixing it!
