### ISSUE TITLE
See devices but doesn't report

### ISSUE THREAD

**Issue by scottriggle** [jason0x43/hacs-hubitat#219] opened 2023-06-19 20:44 UTC
The integration seemed to have worked, I see the devices and I see things like battery level.. etc. But no events are being reported, motion and contact. I contact switch remain closed no matter what. Seeing this in Hubitat the device reports just fine.

Testing the device using curl on my hass server back to Hubitat works fine. I see the correct results of the device when I open a door or something.

**Comment by jason0x43** [comment] 2023-07-13 02:52
When events don't show up in HA, it typically means that Hubitat can't communicate with HA. Usually that's because HA is running in a docker container that's not on the same network as Hubitat, so the default address that the integration sets in Hubitat for the "URL to send device events to by POST" isn't reachable by Hubitat.

Is the device event address in the Maker API app in Hubitat one that Hubitat can see?

**Comment by JohnathonMohr** [comment] 2023-08-05 23:47
I just created #224, could that be what you’re hitting @scottriggle?

**Comment by jason0x43** [comment] 2023-08-10 02:00
I'm closing this because it sounds like things are working, but feel free to re-open it if the issue isn't resolved.

**Closed by jason0x43** 2023-08-10 02:00 UTC
