### ISSUE TITLE
Optional Fields Required?

### ISSUE THREAD

**Issue by ben-bays** [jason0x43/hacs-hubitat#175] opened 2022-07-16 17:29 UTC
I am attempting to re-configure the Hubitat integration from Home Assistant so that it can discover new devices available from Hubitat, but am receiving input validation errors.

<img width="585" alt="image" src="https://user-images.githubusercontent.com/16564653/179365702-2bd90d61-9393-4483-b653-86aea36233a9.png">

If I put a space in the `Server Url` text field, it passes validation and begins to complain about the next field, server port.

**Comment by mbbush** [comment] 2022-07-17 03:29
This is a duplicate of #176, which is resolved in beta version v0.8.1b2

**Closed** 2022-07-17 17:15 UTC
