### ISSUE TITLE
Allow hub temperature units to be specified

### ISSUE THREAD

**Issue by xAPPO** [jason0x43/hacs-hubitat#21] opened 2020-02-23 08:26 UTC
When HE reports values in centigrade they are being treated as fahrenheit and so converted again by HA to centigrade when displayed in HA (using centigrade values)

55 centigrade ..>>..  12 centigrade.

**Comment by jason0x43** [comment] 2020-02-23 15:01
Ah, I think I see the problem. I thought HA was paying attention to a temp_units property in the climate device, but it doesn't look like that's the case. I need to update the logic to convert to and from HA's internal units.

**Comment by jason0x43** [comment] 2020-02-23 22:45
Actually...after looking into it a bit more, HA is using the `temperature_units` property. However, you may be running into the fallback logic.

If the climate device reports which units it's using via the `temperatureUnit` attribute, the integration will use that. If, for some reason, the device either isn't reporting its units, or is reporting a value the integration doesn't understand ("F" or "C"), then the integration guesses the units based in the current temperature.

The guessing logic is that if the current temp is null or is > 50 (an abnormal room temperature for both Centigrade and Fahrenheit, but particularly for Centigrade), then the units are Fahrenheit. Otherwise, they're Centigrade.

So the issue is _probably_ that your climate device isn't reporting its units, or the integration isn't interpreting them properly. If you open the device in Hubitat, in the "Current States" section, do you see a value for `temperatureUnit`? If so, what is it?

**Comment by jason0x43** [comment] 2020-02-24 00:13
Hmmm...for some reason I assumed you were talking about climate devices (thermostats). Were you instead referring to general temperature sensors?

**Comment by jason0x43** [comment] 2020-02-24 00:36
Ah. Probably so. Besides the fact that 55 C would be a weird temperature for a thermostat, I see that I'm always assuming F for general temperature sensors. 🤦‍♂

**Comment by Gledholt** [comment] 2020-02-24 04:06
Sorry - just catching up..    I am actually monitoring temperatures from my boiler relating to the flow, return and hot water temperatures so they do sit in the up to 70°C ish range and some maybe above. I have an oven temperature sensor that goes over 230°C.  These are sensors.  The thermostats seem correct although I have a strange value from Nest although that may have arrived as a sensor value.
![image](https://user-images.githubusercontent.com/55451838/75128110-7da39600-56ba-11ea-9a06-ef11cd806f62.png)

In my MQTT app I have found the UOM and conversion quite reliable - although it caught me out if it was absent. 

Jason, I was just having a look at your app and both the ease of integration from HE > HA and now the range of capabilities supported is much better than mine. In my threads I shall let people that if they are not needing MQTT or HA>HE I would recommend they use your app. Well done, good job.

HA integration has happened in my MQTT app alongside several other HA applications because of HA Auto Discovery, statestream and homie support.   But the demands expand significantly in these areas encompassing apps I don't use so it's great to have an alternative. Choice is good.

Kevin

**Comment by jason0x43** [comment] 2020-02-24 05:31
The root issue is that Hubitat temperature sensors don't advertise their units. The hub has a global setting for temperature units that is used for all the sensors. Unfortunately that data isn't available through the Maker API, so the fix in effca5c is to allow the user to specify the units in HA, both when initially setting up the integration and as an option later on.

**Comment by jason0x43** [comment] 2020-02-24 05:34
The initial fix is in master if you'd like to try it. I'd like to see if I can get HA to update all the sensors when the units are changed; right now it requires a restart of HA to get everything to update.

**Comment by jason0x43** [comment] 2020-02-25 04:11
This this is fully resolved in commit 6eaf05d, which refreshes temperature sensors immediately after an options update.

**Closed by jason0x43** 2020-02-25 04:11 UTC
Labels: enhancement
