### ISSUE TITLE
Hubitat custom integration not handling Roku variables correctly 

### ISSUE THREAD

**Issue by rpiasentin** [jason0x43/hacs-hubitat#288] opened 2024-09-04 21:37 UTC
I think I detected a bug in the way Roku commands are being passed through the Habitat integration. Please take a look at the advance. Deb logging. I pulled from Home Assistant. There appears to be a variable tight mismatch related to power and I suspect this is causing my Roku to come on in the middle of the night when they’re being polled :    

WSource: custom_components/hubitat/hub.py:484
integration: Hubitat ([documentation](https://github.com/jason0x43/hacs-hubitat), [issues](https://github.com/jason0x43/hacs-hubitat/issues))
First occurred: September 3, 2024 at 8:15:53 PM (14 occurrences)
Last logged: 11:53:31 AM

Error handling event <Event device_id="31" device_name="Roku spare (12F536)" attribute="mediaInputSource" value="Roku Dynamic Menu" unit="None" description="None" type="None">: Sensor sensor.roku_spare_12f536_power has device class 'power', state class 'measurement' unit 'W' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'PowerOn' (<class 'str'>)
Error handling event <Event device_id="31" device_name="Roku spare (12F536)" attribute="application" value="Roku Dynamic Menu" unit="None" description="None" type="None">: Sensor sensor.roku_spare_12f536_power has device class 'power', state class 'measurement' unit 'W' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'PowerOn' (<class 'str'>)
Error handling event <Event device_id="15" device_name="Roku master (F2E2BC)" attribute="supportedInputs" value="["Home","Prime Video","Apple TV","Hulu","Disney Plus","Max","Paramount

**Describe the bug**

**To Reproduce**

**Screenshots**

**Environment**

 - Home Assistant version: 
 - Integration version:

**Comment by jason0x43** [comment] 2024-09-04 22:30
Could you get the [capabilities](https://github.com/jason0x43/hacs-hubitat?tab=readme-ov-file#checking-device-capabilities) for your Roku device?

**Comment by jason0x43** [comment] 2024-09-15 21:41
As far as the error goes, the issue is that the Roku driver and the integration don't agree on what a `power` attribute should represent. The integration assumes drivers are following Hubitat's device capabilities spec, and in the spec a `power` attribute is a [power measurement](https://docs2.hubitat.com/en/developer/driver/capability-list#powermeter). The Roku driver, on the other hand, is using that attribute to report a general power state.

> I suspect this is causing my Roku to come on in the middle of the night when they’re being polled.

The integration doesn't poll devices device. However, if you have an automation that's polling the device and trying to make decisions from the `power` attribute, I can see how you might be running into trouble. Ideally I'd say automations should look at the `switch` attribute to tell if the device is on or off, but I'm not sure what that driver is using the `switch` attribute for, so that might not work.

In any case, I'm going to update the integration to consider the device's stated capabilities as well as its attributes when adding power sensors. That should resolve this, although you may need to remove the Roku from the Maker API and re-add it if simply updating the integration doesn't do the trick.

**Comment by jason0x43** [comment] 2024-12-21 21:49
Closing this as resolved (v0.9.35)

**Closed by jason0x43** 2024-12-21 21:49 UTC
