### ISSUE TITLE
Hubitat configuration flow broken with 2022.7.5

### ISSUE THREAD

**Issue by goldbondxyz** [jason0x43/hacs-hubitat#176] opened 2022-07-16 17:50 UTC
Added a few new devices and was prompted by both HA and HE for updates today. When I went to sync the 2 via HA and HE hooks, I receive the following error now within HA Hubitat addon:User input malformed: expected str for dictionary value @ data[‘server_url’]
HE version: 2.3.2.139
HA version: core-2022.7.5
Confirmed HA update broke HE integration for me. Restored back to core_2022.7.3 and the HE integration now works…

**Comment by jason0x43** [comment] 2022-07-16 18:00
Try enabling debug logging and check the HA log for errors. I have HA 2022.7.5 running with the integration, so it _can_ work, but that certainly doesn't mean there isn't an issue. 🙂

**Comment by goldbondxyz** [comment] 2022-07-16 18:15
Looks like something is broken. I just tried BI and same results: User input malformed: <camera> is not a valid option for dictionary value @ data['allowed_camera']

**Comment by goldbondxyz** [comment] 2022-07-16 19:20
I resolve BI by remove/re-add. No such luck with the painful process for HE integration. Same error. Will try the debugging next...

**Comment by goldbondxyz** [comment] 2022-07-16 19:36
> Try enabling debug logging and check the HA log for errors. I have HA 2022.7.5 running with the integration, so it _can_ work, but that certainly doesn't mean there isn't an issue. 🙂

I haven't had to do this before and struggling to determine how this is done.  BI and other components have it build into the integration as an option. Where do I find this for HE integration?

**Comment by goldbondxyz** [comment] 2022-07-16 20:11
Jason, Followed instructions to add debug in configuration.yaml. But, no idea what I am looking for. I don't see anything particularly suspicious in /config/home-assistant.log.  There seems to be reporting from the components as I refresh. 
Is there another log file or something specific to show me when clicking the configure->submit button on the integration causes the above error?

**Comment by mbbush** [comment] 2022-07-17 00:58
I'm having this issue too. If I had to guess, I'd say it's likely related to the python 3.10 upgrade, or perhaps to some new type checking validation added in HA. 

It seems like the issue it's complaining about is that the default value (empty) for each of the optional fields doesn't have the right type (expects a string, but the empty field is probably parsed as `None`). I bet the fix is to use a type which is either string or None. I'll see if I can dig up where that change needs to be made and post a PR if I get a chance.

**Comment by jason0x43** [comment] 2022-07-17 01:14
Oh, I was misunderstanding where the issue is. I see the problem now. When trying to run through the config flow, the integration returns an error when you click 'submit'.

**Comment by jason0x43** [comment] 2022-07-17 01:22
It's something that changed in 2022.7.5; the config flow still works in 2022.7.4.

**Comment by jason0x43** [comment] 2022-07-17 02:34
Try v0.8.1b2.

**Comment by goldbondxyz** [comment] 2022-07-17 03:14
Hey Jason, Thanks for quick response.  Hoping you can help locating the code. All I see is existing build 0.7.2

**Comment by jason0x43** [comment] 2022-07-17 03:23
Open the Hubitat integration in HACS, tap the three-dot menu in the upper right of the screen, choose Redownload, and enable "Show beta versions".

**Comment by mbbush** [comment] 2022-07-17 03:27
v0.8.1b2 fixes the issue for me. Thanks for the quick response!

**Comment by goldbondxyz** [comment] 2022-07-17 03:40
I can confirm that I am up and running with 0.8.1b2 and 2022.7.5. Thanks Jason!!

**Comment by jason0x43** [comment] 2022-07-19 01:39
The fix has been released in v0.8.1.

**Closed by jason0x43** 2022-07-19 01:39 UTC
