### ISSUE TITLE
Unable to install hubitatmaker dependency

### ISSUE THREAD

**Issue by methylmercury** [jason0x43/hacs-hubitat#67] opened 2020-09-18 21:34 UTC
Was working great, can't remember an update, but today I get this error and no hubitat devices are available.

homeassistant@raspberrypi:~/.homeassistant$ cat home-assistant.log | grep hubitatmaker
2020-09-18 13:35:41 ERROR (SyncWorker_20) [homeassistant.util.package] Unable to install package hubitatmaker>=0.3.11,<0.4.0: Could not find a version that satisfies the requirement hubitatmaker<0.4.0,>=0.3.11 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.1.0, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.7, 0.3.8, 0.3.9, 0.3.10)
No matching distribution found for hubitatmaker<0.4.0,>=0.3.11
2020-09-18 13:35:41 ERROR (MainThread) [homeassistant.setup] Setup failed for hubitat: Requirements for hubitat not found: ['hubitatmaker>=0.3.11,<0.4.0'].

**Comment by jason0x43** [comment] 2020-09-18 21:56
Hmmm...you're the second person to mention that. I'm not sure offhand what the issue might be. Both 0.3.11 and 0.3.12 of hubitatmaker have been published to pypi, and both are installable with pip.

Can you try running `pip install hubitatmaker==0.3.12` on your local system and see if it works?

**Comment by methylmercury** [comment] 2020-09-18 22:34
I might not be doing this right, but here is what happened:

**Comment by methylmercury** [comment] 2020-09-19 20:04
Let me know if you want me to try anything else, I'm at a loss to what is wrong but I'm not really knowledgeable in HA and HE, as I just migrated off of SmartThings/WebCore.

**Comment by jason0x43** [comment] 2020-09-19 20:15
Hmmm...I think I might know what the problem is. In HA, go to Config -> Info. What do you have for "python_version"?

**Comment by methylmercury** [comment] 2020-09-19 20:19
From HA->Info:
python_version is 3.7.3

From the command prompt:
homeassistant@raspberrypi:~/.homeassistant$ python --version
Python 2.7.16

IDK why there are two different versions...

**Comment by jason0x43** [comment] 2020-09-20 00:02
They problem is on my end. I recently updated how the hubitatmaker package is built, and as part of that I accidentally changed the minimum required version of Python to 3.7.7. The integration should still work fine with lower versions, though; I'll publish an updated version of the package later tonight.

**Comment by methylmercury** [comment] 2020-09-20 00:39
OH, ok.  I thought I had the most recent version, as I just installed HA last week.

**Comment by jason0x43** [comment] 2020-09-20 13:35
I just published an updated version  of hubitatmaker that will work with Python 3.7.1+. Try restarting HA again and see if it works this time.

**Comment by methylmercury** [comment] 2020-09-20 15:07
Yup, works like a charm now.  Thank you!

**Comment by methylmercury** [comment] 2020-09-25 21:27
Still working great, but I do have one question.  I changed some of the Hubitat drivers from Generic to specific and now I'm seeing duplicates in Home Assistant.  How do I remove them?

**Comment by jason0x43** [comment] 2020-09-26 14:31
Closing this because it appears to be fixed.

I [responded](https://community.home-assistant.io/t/custom-component-hubitat/166750/728) to the removal question  in the forums (basically there's no easy solution at the moment).

**Closed by jason0x43** 2020-09-26 14:31 UTC
