### ISSUE TITLE
Can't find a way to permanently filter out some Habitat devices

### ISSUE THREAD

**Issue by DerekSeaman** [jason0x43/hacs-hubitat#198] opened 2023-03-06 01:56 UTC
I have Maker API running on my Habitat for various purposes, one of which includes this HACS extension. However, I do NOT want all Maker API devices brought into this extension. Yes, I can run the configuration of this extension enough times that I get to a screen where I can "remove" devices. This works one time. If I add additional devices to the Maker API in HE, then in HA when I re-run the config it seems to pull in all Maker API devices and expose them to HA. I have to re-run the extension config yet again to try and remember which devices I need and which ones to 'remove'. 

IMHO, the configuration workflow needs an overhaul. For example, when I click on Configure it would be way more helpful to see three buckets of devices: Those currently exposed to HA, those hidden/removed, and newly discovered devices. Then a check box could let me select/de-select devices to add/remove to HA. And this list should be static between runs, meaning is has memory on which devices are in which bucket. 

This may not be the best solution, but the current UI/UX just isn't working for users that only want selective Maker API devices, and on occasion add new devices but want to maintain the current "filtered" view of devices while adding new ones.

**Comment by jason0x43** [comment] 2023-03-06 15:23
> However, I do NOT want all Maker API devices brought into this extension.

The idea is that the extension should have it's own instance of Maker API on Hubitat (you can run multiple instances of Maker API in Hubitat), and this instance should only expose the devices that should be available in HA.

> Yes, I can run the configuration of this extension enough times that I get to a screen where I can "remove" devices. This works one time.

The main purpose of the "remove" function is to remove devices from HA that have been removed from the Maker API in Hubitat. (Devices aren't auto-removed out of an abundance of caution.) If you remove a device from the integration in HA but the device is still exposed through the Maker API, HA will pick it up again when the integration is reinitialized, such as during a restart.

> IMHO, the configuration workflow needs an overhaul.

You're not wrong, although I don't think the device management process would fundamentally change. 🙂

**Comment by jason0x43** [comment] 2023-04-08 19:14
Closing this as the device exclusion system is working as intended (i.e., devices that shouldn't show up in HA shouldn't be included in the Maker API instance on the Hubitat side).

**Closed by jason0x43** 2023-04-08 19:14 UTC
