### ISSUE TITLE
No way to send refresh command

### ISSUE THREAD

**Issue by jatgm1** [jason0x43/hacs-hubitat#105] opened 2021-02-11 18:22 UTC
It doesn't appear there is any way to manually send the refresh command to temperature/humidity sensors as an action in home assistant as you can in hubitat.

**Comment by jason0x43** [comment] 2021-02-11 18:25
This is a duplicate of #104 (in that the purpose of #104 is exactly this)

**Closed by jason0x43** 2021-02-11 18:25 UTC
