### ISSUE TITLE
Entity Confusion with Multiple Hubitat Integrations

### ISSUE THREAD

**Issue by chadisrad323** [jason0x43/hacs-hubitat#149] opened 2021-11-05 20:21 UTC
I have two Hubitat Elevations integrated into Home Assistant. It works well except for the way entities are associated to devices. If a device on Hub A has the same device number as a device on Hub B, Home Assistant mixes the entities together and randomly shows the device name as either the Hub A or Hub B device. The unique identifier HA uses should be a combination of hub and device number, rather than just the device number. Please see attachment for screenshots and an explanation of the issue I'm experiencing. Otherwise, this integration is fantastic -- thanks for all your work.

[HA Hubitat Device Confusion.pdf](https://github.com/jason0x43/hacs-hubitat/files/7488686/HA.Hubitat.Device.Confusion.pdf)

**Comment by jason0x43** [comment] 2021-11-05 20:34
The unique ID is a combination of a hash of the Maker API token (which is unique per install of Maker API), the device number, and the entity type. Those _should_ be unique per entity, even when devices on different hubs have the same number. But there certainly could be a bug in there somewhere.

Find two of the entities that are being mixed up in the entity registry (`<config>/.storage/core.entity_registry`). Their `unique_id` and `device_id` properties should be different. If they're not, well, that's a problem.

**Comment by chadisrad323** [comment] 2021-11-05 21:32
Thanks for the quick reply. I have attached the entries for the two entities. They do have different unique identifiers, but they have the same device_id, even though they are set up on two separate Hubitat hubs and separate devices.

[core_entity_registry_examples.txt](https://github.com/jason0x43/hacs-hubitat/files/7489041/core_entity_registry_examples.txt)

**Comment by yougotborked** [comment] 2021-11-21 17:48
I'm seeing the same issue here, Depending on the order I "Reload" the integration (2 hubs, 1 focused on zibgee, 1 zwave) 
The "last" device's reloading supersedes the previous.

**Comment by summitbri** [comment] 2021-12-24 00:17
I am about to add a second hubitat to HA.  Is there anything I can do to Hubitat #2 in advance to avoid a problem?

**Comment by yougotborked** [comment] 2021-12-24 00:23
From my understanding of the issue, if you make sure all your device IDs (number at the end of the hubitat device URL) are unique across 2 hubs, that would fix it

**Comment by summitbri** [comment] 2021-12-29 18:44
So after some inspection I've discovered multiple devices, mostly Zwave, that have conflicting device IDs.  Am I able to change these on one hubitat without causing chaos in my system?

**Comment by jason0x43** [comment] 2021-12-29 23:22
I don't believe you can update device IDs on Hubitat (well, other than by removing and re-adding a device). The integration needs to be updated to ensure that devices coming from different hubs have different IDs (which I'll hopefully get to soon).

**Comment by AlohaFlyer** [comment] 2022-05-09 08:16
Any updates on this? I am still experiencing this bug.

**Comment by jason0x43** [comment] 2022-05-09 12:08
Not yet, but I’ll try to take a look this week.

**Comment by chadisrad323** [comment] 2022-05-09 16:53
Thank you, @jason0x43. This will be hugely helpful to those of us with multiple hubs!

**Comment by jason0x43** [comment] 2022-05-11 01:39
I can reproduce the issue on my test system, so that's something.

**Comment by jason0x43** [comment] 2022-05-11 23:59
Progress! I see why unique devices weren't being created for each hub, and how to fix that. Now to figure out a way to cleanly update an installation...

**Comment by AlohaFlyer** [comment] 2022-05-12 00:58
Fantastic! I am running 4 HE hubs. Looking forward to testing this. Thank you

**Comment by jason0x43** [comment] 2022-05-12 01:03
I just published a new [prerelease](https://github.com/jason0x43/hacs-hubitat/releases/tag/v0.7.2b1). This version will create new device entries with unique IDs for everything, but the entity IDs _should_ all be the same. Assuming this works properly outside of my test environment, I'll look into automatically cleaning up leftover devices (right now I've just made it easier to manually clean those up).

**Comment by AlohaFlyer** [comment] 2022-05-12 01:04
Awesome I will give it a go and report back.

**Comment by AlohaFlyer** [comment] 2022-05-12 01:55
Ok I have loaded the new prerelease update, all appears to be working great. 

I did decide to remove the hubitat hubs from HA, and then re-add them.

**Comment by chadisrad323** [comment] 2022-05-12 15:59
This is fantastic news. I'm not sure how to load beta code but looking forward to implementing it soon.

**Comment by chadisrad323** [comment] 2022-06-01 16:32
I have installed this and so far it's working great. Thank you!

**Comment by AlohaFlyer** [comment] 2022-06-02 02:03
Works great! Thank you for the update.

**Comment by AlohaFlyer** [comment] 2022-06-04 12:41
I had 0.7.2b2 and decided to try 0.7.2b4. But it broke my install. All 4 of my hubitats couldn't connect anymore. So I rolled it back to 0.7.2b2 and re-added them. I'm back up and running. I should have screenshot'd the problem but missed my chance.

**Comment by yougotborked** [comment] 2022-06-04 13:40
I had a similar issue. Capture it here

``This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/hubitat/hub.py:522
Integration: Hubitat (documentation, issues)
First occurred: 8:40:07 AM (2 occurrences)
Last logged: 8:40:07 AM

Error setting up entry Hubitat zigbee for hubitat
Error setting up entry Hubitat Zwave for hubitat
Traceback (most recent call last):
  File "/config/custom_components/hubitat/hub.py", line 517, in _update_device_ids
    int(id_set[1])
ValueError: invalid literal for int() with base 10: '6ccc5096'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 339, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/hubitat/__init__.py", line 37, in async_setup_entry
    if not await hub.async_setup():
  File "/config/custom_components/hubitat/hub.py", line 292, in async_setup
    _update_device_ids(self.id, self.hass)
  File "/config/custom_components/hubitat/hub.py", line 522, in _update_device_ids
    dev_id = id_set[1].split(":")[1]
IndexError: list index out of range

**Comment by jason0x43** [comment] 2022-06-05 00:01
Thanks for the error log! I think I see what's happening; the identifier update code isn't handling multiple hub IDs properly. I should have an update out shortly.

**Comment by jason0x43** [comment] 2022-06-05 00:21
I just published v0.7.2b5 which should take care of that issue.

**Comment by yougotborked** [comment] 2022-06-05 03:03
V5 looks good. No error. thanks

**Comment by AlohaFlyer** [comment] 2022-06-05 06:12
v0.7.2b5 seems to be working great for me and my 4 Hubitat hubs. Thank you for the quick fix. 😎

**Comment by jason0x43** [comment] 2022-06-10 02:41
Resolved in release 0.7.2.

**Closed by jason0x43** 2022-06-10 02:41 UTC
Labels: bug

**Comment by AlohaFlyer** [comment] 2022-06-10 06:01
Thank you for the fix 🙏
