### ISSUE TITLE
After upgrade to 0.7.2 new devices added to Hubitat not discovered by HA

### ISSUE THREAD

**Issue by acato** [jason0x43/hacs-hubitat#173] opened 2022-06-19 18:25 UTC
I have added two generic zigbee door sensors to the Hubitat hub, one before upgrading from 0.7.1 to 0.7.2, one after. The one added before was easy to discover going through the configuration flow in the HA UI after it was paired with Hubitat, but the second one was never picked up. Also, removing a sensor and then readding is no longer discovered. 
I have no workaround so far.

**Comment by jason0x43** [comment] 2022-06-20 13:33
Hmmm...I haven't been able to reproduce that issue. Do you see any errors in the log? (Ensure [debug logging](https://github.com/jason0x43/hacs-hubitat#logging) is enabled.)

You might also try 1) reloading the extension using the "Reload" menu item in the integration options, or 2) restarting HA.

**Comment by acato** [comment] 2022-06-21 06:17
Uninstalling and reinstalling the integration fixed it. It looks like I had some lint in my configuration,

**Comment by jason0x43** [comment] 2022-06-21 11:07
Glad to hear things are working again! 🙂

**Comment by jason0x43** [comment] 2022-07-12 18:57
Since things seem to be working, I'm closing this one out.

**Closed by jason0x43** 2022-07-12 18:57 UTC
